name: releaseFromMaster

on:
  push:
    branches:
      - "master"
env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  HOST: ${{ secrets.HOST }}
  HTTP_PORT: ${{ secrets.HTTP_PORT }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  NETWORK: ${{ secrets.NETWORK }}
  REGISTRY: ${{ secrets.REGISTRY }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY: ${{ secrets.KEY }}
  PHRASE: ${{ secrets.PHRASE }}

  # MONGO_URI: ${{ secrets.MONGO_URI }}
jobs:
  # crear env file de forma piola la respujesta de base64 esta piola
  # https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions
  build_and_push:
    name: Build and push to DigitalOcean private registry
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FRONTEND_URL: ${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
      NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Create .env
        run: |
          touch .env
          echo "NEXT_PUBLIC_FRONTEND_URL=${{env.NEXT_PUBLIC_FRONTEND_URL}}" >> .env
          echo "NEXT_PUBLIC_BACKEND_URL=${{env.NEXT_PUBLIC_BACKEND_URL}}" >> .env
          cat .env
        working-directory: ./
      - name: Docker build
        run: |
          docker build -t ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ github.sha }} .
          docker build -t ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest .
        working-directory: ./
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_ACCESS_TOKEN}}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push  ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ github.sha }}
          docker push  ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
  deploy:
    name: Deploy to DigitalOcean Docker Droplet
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          passphrase: ${{ env.PHRASE }}
          envs: IMAGE_NAME,REGISTRY
          script: |
            doctl registry login --expiry-seconds 600
            docker stop ${{env.IMAGE_NAME}} || true
            docker rm ${{env.IMAGE_NAME}} || true
            docker rmi ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest || true
            docker run -d --name ${{env.IMAGE_NAME}} -p ${{env.HTTP_PORT}}:${{env.HTTP_PORT}} --network ${{env.NETWORK}} ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest